<a href="https://colab.research.google.com/github/sanskritidhar79/Python/blob/main/Assingment3LAB_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a program that has a class Student for storing roll number, name, and marks in five subjects of a student. Display the information stored about the student.


In [ ]:
class Student:
  def __init__(self , roll_number , name , marks):
    self.roll_number = roll_number
    self.name = name
    self.marks= marks
  def display_info(self):
    print(" ******** Student Information *******")
    print("Roll number" , self.roll_number)
    print("Name " , self.name)
    for i in range(len(self.marks)):
      print("marks in Subject" , i+1, " are ", self.marks[i] )

roll_num = int(input("Enter roll number"))
name = input("Enter name")
marks =[]
for i in range(5):
  marks.append(int(input("Enter marks")))

s = Student(roll_num, name, marks)
s.display_info()



Enter roll number1
Enter nameben
Enter marks90
Enter marks0
Enter marks90
Enter marks90
Enter marks90
 ******** Student Information *******
Roll number 1
Name  ben
marks in Subject 1  are  90
marks in Subject 2  are  0
marks in Subject 3  are  90
marks in Subject 4  are  90
marks in Subject 5  are  90


2. Write a program to create a derived class employee derived from the class basicinformation(member variables are name, empid, and age) and departmentinformation(member variables are dept name, assigned work, and time to complete) using multiple inheritances. Create two objects of employee class and print the details of individual objects.


In [ ]:
class BasicInformation:
  def __init__(self , name , empid , age):
    self.name = name
    self.empid = empid
    self.age = age

  def display_basic_info(self):
    print(" Name is : " ,self.name , " employee id is " ,self.empid , " age is : " , self.age )


class DepartmentInformation:
  def __init__(self , dept_name , assigned_work , time_to_complete):
    self.dept_name = dept_name
    self.assigned_work = assigned_work
    self.time_to_complete = time_to_complete

  def display_dept_info(self):
    print("Department name is  :  " , self.dept_name , " Assinsged Work is " , self.assigned_work , " time to compelete is " , self.time_to_complete)

class Employee(BasicInformation , DepartmentInformation):
  def __init__(self , name , empid , age , dept_name , assigned_work , time_to_complete):
    BasicInformation.__init__(self , name , empid , age)
    DepartmentInformation.__init__(self , dept_name , assigned_work ,time_to_complete)

  def display_employee_info(self):
    self.display_basic_info()
    self.display_dept_info()


'''
name = input("Enter name")
empid = int(input("Enter empid"))
age = int(input("Enter age"))
dept_name = input("Enter dept name")
assigned_work = input("Enter assigned work")
time_to_complete = int(input("Enter time to complete"))
'''

e1 = Employee("Ben" , 1 , 20 , "AI and DS" , "Python", "1 hour")
e1.display_employee_info()

print()

e2 = Employee("Sheldon" , 2 , 21 , "AI and DS" , "Linear Alzebra", "2 hour")
e2.display_employee_info()



 Name is :  Ben  employee id is  1  age is :  20
Department name is  :   AI and DS  Assinsged Work is  Python  time to compelete is  1 hour

 Name is :  Sheldon  employee id is  2  age is :  21
Department name is  :   AI and DS  Assinsged Work is  Linear Alzebra  time to compelete is  2 hour


3. Write a program that has a class Person. Inherit a class Faculty from Person which also has a class Publication.


In [ ]:

class Person :
  def __init__(self ,name , id  , age ):
    self.name = name
    self.id = id
    self.age = age

  def display_Person(self):
    print("Name is , " , self.name , " ID is  , " , self.id , "age is , " , self.age)


class Faculty(Person):
  def __init__(self, name , id , age,subject , department):
    super().__init__(name , id , age)
    self.subject = subject
    self.department = department

  def display_Faculty(self):
    self.display_Person()
    print("Subject is , " , self.subject , " Department is , " , self.department)



class Publication(Faculty):
  def __init__(self , journal_name , published_date ,name , id , age,subject , department ):
    super().__init__(name , id  , age , subject, department)
    self.journal_name = journal_name
    self.published_date = published_date

  def display_Publication(self):
    self.display_Faculty()
    print("Journal name is ," , self.journal_name , "Published date is , " , self.published_date)



p = Publication("IEEE" , "2025 ", "Ben " , 1 , 20 , "Computer Science" , "Python")
p.display_Publication()




Name is ,  Ben   ID is  ,  1 age is ,  20
Subject is ,  Computer Science  Department is ,  Python
Journal name is , IEEE Published date is ,  2025 


4. Write a program that has an abstract class Polygon. Derive two classes Rectangle and Triangle from Polygon and write methods to get the details of their dimensions and hence calculate the area.


In [ ]:
from abc import ABC, abstractmethod
class Polygon(ABC):

  @abstractmethod
  def getDimensions(this):
    pass

  @abstractmethod
  def calcArea(this):
    pass

class Rectangle(Polygon):
  """
  def __init__(this , length, width):
    this.length = length
    this.width = width
  """

  def getDimensions(this):
    l = float(input("Enter length of rectangel"))
    w = float(input("Enter width of rectangel"))
    this.width = w
    this.length = l

  def calcArea(this):
    print("Area of rectangle is " ,  this.length * this.width)

class Triangle(Polygon):
  """
  def __init__(this , base, height):
    this.base = base
    this.height = height
  """

  def getDimensions(this):
    b = float(input("Enter base of Triangle "))
    h = float(input("Enter height of the Triangle "))
    this.base = b
    this.height = h

  def calcArea(this):
    print("area of Triangle is " ,  0.5 * (this.base) * (this.height))


choice = int(input(" Enter 1 for Rectangle  , enter 2 for traingle"))

if choice == 1:
  r = Rectangle()
  r.getDimensions()
  r.calcArea()
elif choice == 2:
  t = Triangle()
  t.getDimensions()
  t.calcArea()
else :
  print("Invalid Choice")






 Enter 1 for Rectangle  , enter 2 for traingle2
Enter base of Triangle 12
Enter height of the Triangle 14
area of Triangle is  84.0


5.Write a Python program to create a NumPy array of shape
5×2 filled with ones.


In [ ]:
import numpy as np
np.ones((5, 2), dtype=int)


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

6. Write a Python program to create a 1D NumPy array of 10
random numbers between 0 and 1.


In [ ]:
print(np.random.rand(10))

[0.26356372 0.78782554 0.23759069 0.2698044  0.75667519 0.39705375
 0.58280031 0.34720666 0.2998333  0.31207189]


7 .
Write a Python program to reshape a 1×9 array into a 3×3
matrix


In [ ]:
def reshapeArray():
  arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
  #print(arr.size)
  new_arr = arr.reshape(3,3)
  print(new_arr)

reshapeArray()


9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


8.
Write a Python program to create a NumPy array of even
numbers between 10 and 30.


In [ ]:
def evenArray():
  arr = np.arange(10 , 31, 2)
  print(arr)
evenArray()

[10 12 14 16 18 20 22 24 26 28 30]


9 .
Write a Python program to create a NumPy array with 10
linearly spaced numbers between 0 and 5.


In [ ]:
def linearArray():
  arr = np.linspace(0 , 5 , 10)
  print(arr)
linearArray()

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


10. Write a Python program to find the mean, median, and standard deviation of the elements in a NumPy array.


In [ ]:
def summaryStats():
  arr = np.array([1,2,3,4,5,6,7,8,9])
  print(" Mean is  " , np.mean(arr))
  print(" Median is " , np.median(arr))
  print(" Standared Deviations is " , np.std(arr))

summaryStats()

 Mean is   5.0
 Median is  5.0
 Standared Deviations is  2.581988897471611


11. Write a Python program to flatten a 3×3 NumPy array into a 1D array.


In [ ]:
def flatten_arr():
  arr = np.array([[1,2,3] , [4,5,6] , [8,9,0]])
  flatten_arr_res = arr.flatten()
  print(flatten_arr_res)
  print(flatten_arr_res.size)

flatten_arr()

[1 2 3 4 5 6 8 9 0]
9


12. Write a Python program to perform element-wise addition of two NumPy arrays.


In [ ]:
def elementAddition():
  arr1 = np.array([4,5,6])
  arr2 = np.array([1,2,3])

  print(np.add(arr1 , arr2))

elementAddition()


[5 7 9]


13.Write a Python program to find the dot product of two 1D
NumPy arrays (vectors)


In [ ]:
def dotProduct():
  vector1 = np.array([1,2,3])
  vector2 = np.array([4,5,6])

  print(np.dot(vector1 , vector2))

dotProduct()


32


32

14. Write a Python program to find the cross product of two 1D
NumPy arrays (vectors).


In [ ]:
def crossProduct():
  vector1 = np.array([1,2,3])
  vector2 = np.array([4,5,6])
  print(np.cross(vector1 , vector2))

crossProduct()



[-3  6 -3]


15. Write a Python program to check if a set is a subset of another set.


In [ ]:
def subsetCheck():
  set1 = {1,2,3,4,5}
  set2 = {4,3}

  if set1.issubset(set2):
    print("  Set 1 is Subset of  Set 2")
  else :
    print("Set2 is subset of Set 1 ")

subsetCheck()


Set2 is subset of Set 1 
